<?php

namespace MY\MoneyBundle\Entity;

use \Doctrine\ORM\EntityRepository;
/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM MYMoneyBundle:Bank p ORDER BY p.name ASC'
            )
            ->getResult();
    }
}
