<?php

namespace MY\MoneyBundle\Entity;

/**
 * PaymodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymodeRepository extends \Doctrine\ORM\EntityRepository
{
}
