services:
#    my_user.example:
#        class: MY\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    my_user.form.profile.type:
        class: MY\UserBundle\Form\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: my_fos_user_profile }

    my_user.form.register.type:
        class: MY\UserBundle\Form\RegisterType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: my_fos_user_register }